package app

import "testing"

// The corpus freezes what AISecretKind says about hand-written titles, written
// the way people write requests and tasks, secrets among them. A change to the
// check that moves any row fails here, so that it is made on purpose: move the
// row to the table that now describes it. Every value is made up or public:
// tokens are typed by hand or built from EXAMPLE, zeros, alphabet runs and the
// MD5 of "7", cards and AWS keys are published test values, content IDs are
// public, phone numbers are zeros or unassigned, emails are at example.com,
// and hosts are example, acme, local or public services. Provider tokens,
// webhook, MongoDB and Azure SAS links, the JWT and the private key headers,
// but not the AWS examples, are split into two literals so that secret
// scanners do not flag the file; keep them split.

// aiSecretCorpusCaught are titles that hold a credential, with the kind the
// check names.
var aiSecretCorpusCaught = []struct{ text, kind string }{
	// Values named in running text or after a colon, and inside links.
	{"Сменить пароль для роутера на Qwerty123", "a password or secret"},
	{"Change password for wifi to Hunter2024!", "a password or secret"},
	{"Reset password for user123 to Winter2026!", "a password or secret"},
	{"Update password for bank: S3cure!pass", "a password or secret"},
	{"Поменять пароль для почты: солнышко", "a password or secret"},
	{"reset link example.com/reset?token=8f14e45fceea167a5a36dedd4bea2543", "a key or token"},
	{"[reset](https://example.com/reset?token=8f14e45fceea167a5a36dedd4bea2543)", "a key or token"},
	{"Пароль от сейфа: 2010", "a password or secret"},
	{"пароль от почты: солнышко", "a password or secret"},
	{"OTP 482913", "a PIN or code"},
	{"login admin pass: hunter", "a password or secret"},
	{"Пароль от wifi: correct horse battery staple", "a password or secret"},
	{"Пароль от почты: радость", "a password or secret"},
	{"Код от сейфа: семь восемь", "a PIN or code"},
	{"Пароль от роутера на даче: qwerty123", "a password or secret"},
	{"Gym pass: 4821", "a password or secret"},
	{"Секретное слово: ромашка", "a password or secret"},
	{"Кодовое слово: ромашка", "a PIN or code"},
	{"Guest pass: Welcome2024", "a password or secret"},
	{"https://user:S3cretPass@host.example.com/db", "a password or secret"},
	{"wifi password hunter2", "a password or secret"},
	{"пароль от wifi qwerty123", "a password or secret"},
	{"wifi password: correct horse battery staple", "a password or secret"},
	{"backup codes 38291047 55012934", "a PIN or code"},
	{"2FA recovery codes 3829-1047 5501-2934", "a card number"},
	{"reset link https://example.com/reset?token=8f14e45fceea167a5a36dedd4bea2543", "a key or token"},
	{"Stripe key sk_" + "live_51H8xYzAbCdEfGhIjKlMnOpQr", "a long random-looking token"},
	{"код подъезда 2580", "a PIN or code"},
	{"milk and wifi password: hunter2", "a password or secret"},

	// Codes, passes and links whose rules sit close to ordinary titles.
	{"Reset the password for bob Qwerty123!", "a password or secret"},
	{"Change my password for Netflix Summer2026!", "a password or secret"},
	{"Update my password for bank S3cure!pass", "a password or secret"},
	{"Сменить мой пароль для Госуслуг Qwerty!2026", "a password or secret"},
	{"OTP 4821", "a PIN or code"},
	{"Swiggy delivery OTP 4821", "a PIN or code"},
	{"2FA code 4821", "a PIN or code"},
	{"one-time code 48213", "a PIN or code"},
	{"Pass wifi Kv45dacha", "a password or secret"},
	{"pass от роутера Kv45_dacha", "a password or secret"},
	{"postgres://app:Xy7(kL9)p@db.acme.io:5432/prod", "a password or secret"},
	{"mysql://root:it's-Secret9@localhost:3306/app", "a password or secret"},
	{"ftp://admin:pa(ss)w0rd@ftp.example.com", "a password or secret"},
	{"Hotel pass: 4821", "a password or secret"},

	// A new password after the account it is reset for.
	{"Reset password for a b c d e Qwerty123!", "a password or secret"},
	{"Reset password for bob Qwerty123!", "a password or secret"},
	{"Reset password for admin Winter2026!", "a password or secret"},
	{"Сбросить пароль для admin Qwerty123!", "a password or secret"},
	{"Change password for wifi Hunter2024!", "a password or secret"},
	{"Update password for bank S3cure!pass", "a password or secret"},
	{"Reset password for bob for alice to Qwerty123!", "a password or secret"},
	{"Reset password for bob, new one Qwerty123!", "a password or secret"},
	{"Reset password for bob - Qwerty123!", "a password or secret"},
	{"Reset password for bob (Qwerty123!)", "a password or secret"},
	{"Reset password for bob = Qwerty123!", "a password or secret"},
	{"Сменить пароль для роутера, новый Qwerty123", "a password or secret"},
	{"Сменить пароль для роутера - Qwerty123", "a password or secret"},
	{"Change password for the guest wifi network: Welcome2024!", "a password or secret"},
	{"Сменить пароль для входа в личный кабинет банка на Qwerty123", "a password or secret"},
	{"Change password for account user@example.com to Qwerty123!", "a password or secret"},

	// Credentials by kind: keys, tokens, links, cards and labels.
	{"wifi пароль Кв45_дача!", "a password or secret"},
	{"Пароль от госуслуг: Masha1987!", "a password or secret"},
	{"Password for Netflix is netflixAndChill22", "a password or secret"},
	{"my gmail pw = Summer2026", "a password or secret"},
	{"Wi-Fi: HomeNet / pass: tr0ub4dor&3", "a password or secret"},
	{"Door code 4821#", "a PIN or code"},
	{"Код от подъезда 2580", "a PIN or code"},
	{"Код домофона 45К1234", "a PIN or code"},
	{"Card 4111 1111 1111 1111 exp 12/27 CVV 123", "a card number"},
	{"Карта 5555 5555 5555 4444, CVC 321", "a card number"},
	{"CVV 123 for the Visa ending 4242", "a card security code"},
	{"Reset link https://app.example.com/reset-password?token=Zq8x4Nw2Lp7Kd9Rt", "a key or token"},
	{"Magic link https://example.com/login?code=8f14e45fceea167a5a36dedd4bea2543", "a long random-looking token"},
	{"DB: postgres://admin:S3cr3tPass@db.acme.io:5432/prod", "a password or secret"},
	{"mongodb+srv://app:" + "hunter2@cluster0.ab1cd.mongodb.net/test", "a password or secret"},
	{"redis://:p4ssw0rd@cache.acme.io:6379/0", "a password or secret"},
	{"AWS AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY", "an AWS access key"},
	{"ghp_" + "1234567890abcdefghijABCDEFGHIJ123456", "a GitHub token"},
	{"xox" + "b-123456789012-1234567890123-AbCdEfGhIjKlMnOpQrStUvWx", "a Slack token"},
	{"JWT eyJhbGciOiJIUzI1NiJ9." + "eyJzdWIiOiJFWEFNUExFIn0.EXAMPLE-signature-0000", "a JSON web token"},
	{"-----BEGIN OPENSSH PRIVATE " + "KEY-----", "a private key"},
	{"-----BEGIN RSA PRIVATE " + "KEY-----", "a private key"},
	{"OpenAI sk-" + "proj-AbCdEf1234567890GhIjKlMnOpQr", "an API key"},
	{"Stripe sk_" + "live_EXAMPLEaBcD1234eFgH5678iJkL", "a long random-looking token"},
	{"Telegram bot 123456789:" + "AAEXAMPLE0000EXAMPLE0000EXAMPLE0000", "a webhook or bot token"},
	{"Telegram bot token 123456789:" + "AAEXAMPLE0000EXAMPLE0000EXAMPLE0000", "a webhook or bot token"},
	{"Slack webhook https://hooks.slack.com/services/T0123ABCD/" + "B0123ABCD/AbCdEfGhIjKlMnOpQrStUvWx", "a webhook or bot token"},
	{"Discord webhook https://discord.com/api/webhooks/123456789012345678/" + "AbCdEfGhIjKlMnOpQrStUvWxYz0123456789_AbCdEfGhIjKlMnOpQrStUvWxYz01", "a webhook or bot token"},
	{"Zoom https://us02web.zoom.us/j/00000000000?pwd=EXAMPLE0000EXAMPLE0000", "a password or secret"},
	{"Server=db;Database=prod;User Id=sa;Password=Str0ng!Pass;", "a password or secret"},
	{"export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY", "a long random-looking token"},
	{"Wi-Fi key: sunflower88", "a key or token"},
	{"WPA2 key sunflower88", "a key or token"},
	{"Логин user, пароль: user2026", "a password or secret"},
	{"PIN: 0000", "a PIN or code"},
	{"ПИН карты Сбер 4821", "a PIN or code"},
	{"Recovery codes: 8f14-e45f ceea-167a", "a PIN or code"},
	{"Backup codes 12345678 87654321", "a PIN or code"},
	{"Госуслуги: логин 89000000000 пароль Qwerty!2026", "a password or secret"},
	{"amqp://guest:Rabb1tPass@mq.acme.io:5672/", "a password or secret"},
	{"WiFi: пароль 80000000000", "a password or secret"},
	{"github_pat_" + "11ABCDEFG0123456789_abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOP", "a GitHub token"},
	{"npm_" + "AbCdEfGhIjKlMnOpQrStUvWxYz0123456789", "a long random-looking token"},
	{"Google OAuth GOCSPX" + "-AbCdEfGhIjKlMnOpQrStUvWxYz12", "a long random-looking token"},
	{"Azure SAS https://acct.blob.core.windows.net/c/b.txt?sp=r&st=2026-09-16T10:00:00Z&se=2026-09-17T10:00:00Z&spr=https&sv=2022-11-02&sr=b&sig=" + "AbCdEfGhIjKlMnOpQrStUvWxYz0123456789%2BabcdE%3D", "a key or token"},
	{"S3 https://acme.s3.amazonaws.com/f.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20260916%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260916T100000Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=8f14e45fceea167a5a36dedd4bea25438f14e45fceea167a5a36dedd4bea2543", "an AWS access key"},
	{"Сменить пароль от госуслуг на Qwerty!2026", "a password or secret"},
	{"Change the wifi password to sunflower88", "a password or secret"},
	{"Новый пароль от wifi Kv45dacha", "a password or secret"},
	{"пароль для входа в личный кабинет: Masha1987", "a password or secret"},
	{"SSH root@203.0.113.7 pass Tr0ub4dor&3", "a password or secret"},
	{"jdbc:postgresql://db.acme.io:5432/prod?user=app&password=S3cret", "a password or secret"},
	{"[db](postgres://app:S3cret9@db.acme.io/prod)", "a password or secret"},
	{"admin panel https://admin.acme.io/login?user=root&pass=Tr0ub4dor", "a key or token"},

	// More codes, passes, keys, cards and labels.
	{"backup code A3F9", "a PIN or code"},
	{"Pass wifi: Kv45dacha", "a password or secret"},
	{"Pass: Kv45dacha", "a password or secret"},
	{"WPA key: 8f3kd92l", "a key or token"},
	{"Wireless key 8f3kd92lx", "a key or token"},
	{"Password reset: Qwerty123!", "a password or secret"},
	{"Token refresh: солнышко", "a key or token"},
	{"Card 4111 1111 11111111", "a card number"},
	{"Card 4111111111111111 exp 12/27", "a card number"},
	{"Карта 4111-1111-1111-1111", "a card number"},
	{"Amex 3782 822463 10005", "a card number"},
	{"СМС-код: 482913", "a PIN or code"},
	{"SMS-code 482913", "a PIN or code"},
	{"SMS-код 482913", "a PIN or code"},
	{"sms-codes 482913", "a PIN or code"},
}

// aiSecretCorpusOrdinary are titles that hold no credential.
var aiSecretCorpusOrdinary = []string{
	// Accounts a password is reset for.
	"Reset password for user example_user",
	"Сбросить пароль для user123 в админке",
	"Сменить пароль для роутера TP-Link Archer C6",
	"Reset password for john.doe@example.com",
	"Reset the password for the admin account on staging",

	// Shopping, travel, contacts, links, dev work and labels.
	"Купить молоко, хлеб и яйца к завтраку",
	"Buy AA batteries x4 and HDMI cable 2m",
	"Заказать кроссовки https://www.wildberries.ru/catalog/123456789/detail.aspx?targetUrl=GP",
	"Anker charger https://www.amazon.com/Example-Portable-Charger/dp/B00EXAMPLE/ref=sr_1_3?crid=0EXAMPLE0CRID&keywords=charger&qid=1694012345&sprefix=charger%2Caps%2C182&sr=8-3",
	"AliExpress чехол https://aliexpress.ru/item/1005006141234567.html?sku_id=12000036001234567&spm=a2g2w.productlist.search_results.0",
	"Яндекс Маркет https://market.yandex.ru/product--smartfon-apple-iphone-15/1234567890?sku=102345678901&uniqueId=924574&do-waremd5=Aa1Bb2Cc3Dd4Ee5Ff6Gg7H",
	"Авито велосипед https://www.avito.ru/moskva/velosipedy/gornyy_velosiped_1234567890?context=H4sIAAAAAAAA_wE_AMD_YToyOntzOjEzOiJsb2NhbFByaW9yaXR5IjtiOjA7fQ",
	"Ozon заказ 12345678-0012 забрать в ПВЗ до 20.09",
	"Check in for flight SU 1234 at 10:30, seat 12A",
	"Бронь отеля 1234567, заезд 15.10, выезд 18.10",
	"Train tickets RZD order 70000000000000",
	"Airbnb https://www.airbnb.com/rooms/12345678?check_in=2026-10-01&check_out=2026-10-05&source_impression_id=p3_1726412345_P3xYzAbCdEfGhIjK",
	"Route https://www.google.com/maps/dir/?api=1&destination=Red+Square",
	"Карта https://yandex.ru/maps/-/CD0000~0",
	"Tracking 1Z999AA10123456784 UPS arrives Friday",
	"Трек-номер RA123456789CN проверить на почте",
	"Maps https://maps.app.goo.gl/AbCdEfGhIjKlMnOp9?g_st=ic",
	"Read https://docs.google.com/document/d/1AbCdEfGhIjKlMnOpQrStUvWxYzEXAMPLE0000000000/edit?usp=sharing",
	"Watch https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=42s",
	"Loom https://www.loom.com/share/1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d?sid=0f1e2d3c-4b5a-6978-8a9b-0c1d2e3f4a5b",
	"Notion https://www.notion.so/acme/Q4-planning-8f14e45fceea167a5a36dedd4bea2543?pvs=4",
	"Статья https://habr.com/ru/articles/812345/?utm_source=habrahabr&utm_medium=rss&utm_campaign=812345",
	"VK видео https://vk.com/video-12345678_456239017?list=ln-AbCdEfGhIjKlMnOpQr",
	"Folder https://drive.google.com/drive/folders/1AbCdEfGhIjKlMnOpQrStUvWxYz?usp=drive_link",
	"Shorts https://youtube.com/shorts/AbCdEfGhIjK?si=Qx7LmN2pR8sT4vW9",
	"Sheet https://docs.google.com/spreadsheets/d/1AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefg/edit#gid=1234567890",
	"Slides https://docs.google.com/presentation/d/1AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefg/edit#slide=id.g2f1a3b4c5d6_0_12",
	"Teams https://teams.microsoft.com/l/meetup-join/19%3ameeting_RVhBTVBMRS1tZWV0aW5nLTAwMDAwMDAw%40thread.v2/0?context=%7b%22Tid%22%3a%2200000000-0000-0000-0000-000000000000%22%7d",
	"SharePoint https://acme-my.sharepoint.com/:w:/g/personal/john_acme_com/EbCdEfGhIjKlMnOpQrStUvWBx1y2z3A4b5C6d7E8f9G0hIj?e=AbC1dE",
	"Miro https://miro.com/app/board/uXjVMabcdEF=/?share_link_id=123456789012",
	"Calendly https://calendly.com/example/30min?month=2026-10",
	"Order #112-3456789-1234567 arriving Tuesday",
	"СДЭК 1234567890 забрать до пятницы",
	"Возврат по заказу 12345678-0002, код возврата уточнить",
	"Позвонить маме +7 (900) 000-00-00",
	"Call dentist (555) 123-4567 ext 89",
	"WhatsApp Ahmed +44 7700 900123",
	"Номер курьера 8 900 000 00 00",
	"Доставка: ул. Примерная 12, кв. 45, подъезд 3, этаж 7",
	"Address: 221B Baker Street, London NW1 6XE",
	"Забрать ключи от квартиры у соседа в кв. 12",
	"Ключи от машины: у Пети в офисе",
	"Meeting notes: Q3 roadmap, action items for Anna",
	"1:1 with Bob: discuss promo and feedback",
	"Standup: blockers - waiting on API keys from vendor",
	"Retro: password reset emails delayed on staging",
	"Созвон с командой в 15:00, ссылка в календаре",
	"Implement token refresh in auth middleware",
	"Fix password reset flow on mobile (AUTH-482)",
	"API key rotation for staging and prod",
	"Review PR #482: rotate API keys automatically",
	"Migrate secrets to AWS Secrets Manager by Q4",
	"Rotate AWS access keys for CI user",
	"Investigate 401 on token exchange after deploy 2026-09-15",
	"Code review https://github.com/acme/api/pull/482/files#diff-8f14e45fceea167a5a36dedd4bea2543a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6R120",
	"MR https://gitlab.com/acme/api/-/merge_requests/97/diffs?commit_id=8f14e45fceea167a5a36dedd4bea2543a1b2c3d4",
	"PROJ-1234: Password reset flow returns 500",
	"AUTH-512: token refresh fails after 3600s",
	"[AUTH-77] Token expiry off by one",
	"Update OAuth client secret in GitHub Actions",
	"Hotfix: OTP not sent to +7 900 000 00 00",
	"Sentry https://acme.sentry.io/issues/4512345678/?project=1234567&query=is%3Aunresolved&referrer=issue-stream",
	"Grafana https://grafana.acme.io/d/AbCdEfGhI/api-latency?orgId=1&from=now-6h&to=now&var-env=prod",
	"JIRA https://acme.atlassian.net/browse/AUTH-482?focusedCommentId=123456&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel",
	"Confluence https://acme.atlassian.net/wiki/spaces/ENG/pages/123456789/Runbook+Token+Rotation",
	"CI run https://github.com/acme/api/actions/runs/10812345678/job/30012345678?pr=482",
	"Compare https://github.com/acme/api/compare/v1.2.3...8f14e45fceea167a5a36dedd4bea2543a1b2c3d4",
	"Slack thread https://acme.slack.com/archives/C01ABCDEF12/p1726412345678901?thread_ts=1726412345.678901&cid=C01ABCDEF12",
	"Figma https://www.figma.com/file/AbCdEfGhIjKlMnOp/Design?type=design&node-id=0-1&mode=design&t=AbCdEfGhIjKlMnOp-0",
	"Google Meet https://meet.google.com/abc-defg-hij?authuser=0",
	"Stack Overflow https://stackoverflow.com/questions/12345678/how-to-refresh-jwt#comment123456_12345678",
	"PR https://github.com/acme/web/pull/1234#pullrequestreview-2345678901",
	"Linear https://linear.app/acme/issue/ENG-123/token-refresh-race",
	"Coursera https://www.coursera.org/learn/machine-learning?action=enroll&authMode=signup",
	"TikTok https://www.tiktok.com/@user/video/7412345678901234567?is_from_webapp=1&sender_device=pc&web_id=7412345678901234567",
	"Reddit https://www.reddit.com/r/golang/comments/1abcdef/token_bucket/?share_id=Xk2pL9qRtV7mZ3nB8wYc4&utm_content=1&utm_medium=ios_app",
	"X post https://x.com/user/status/1834567890123456789?s=46&t=Xk2pL9qRtV7mZ3nB8wYc4A",
	"LinkedIn https://www.linkedin.com/posts/example-user_ai-activity-7241234567890123456-AbCd?utm_source=share&utm_medium=member_ios&rcm=ACoAAAbCdEfGhIjKlMnOpQrStUvWxYz0123456",
	"Threads https://www.threads.net/@user/post/C9xYz12AbCd?xmt=AQGzAbCdEfGhIjKlMnOpQrStUvWxYz0123456789",
	"Telegram https://t.me/c/1234567890/123?thread=45",
	"Podcast https://open.spotify.com/episode/4cOdK2wGLETKBW3PvgPWqT?si=Zk3pXq7LwT9mRbV2&context=spotify%3Ashow%3A0AbCdEfGhIjKlMnOpQrStU",
	"Apple Music https://music.apple.com/ru/album/some-album/1234567890?i=1234567891",
	"Photos https://photos.app.goo.gl/AbCdEfGhIjKlMnOp9",
	"Kinopoisk https://www.kinopoisk.ru/film/326/?utm_referrer=www.google.com",
	"Reel https://www.instagram.com/reel/C9xYz12AbCd/?utm_source=ig_web_copy_link&igshid=RVhBTVBMRTk4NzY1NDMyMTA=",
	"Google Docs comment https://docs.google.com/document/d/1AbCdEfGhIjKlMnOpQrStUvWxYzEXAMPLE0000000000/edit?disco=AAABKx1y2z3#heading=h.8f14e45fceea",
	"YouTube timestamp youtu.be/dQw4w9WgXcQ?t=42&si=Zk3pXq7LwT9mRbV2",
	"Wildberries app https://www.wildberries.ru/catalog/123456789/detail.aspx?size=987654321&utm_source=share",
	"Token refresh: handle 401 retry",
	"Password reset: email template broken",
	"OTP 2FA flow: test on staging build 20260915",
	"Password reset flow: add rate limiting",

	// Share links, labels, order numbers and other titles that name a credential in passing.
	"Watch https://youtu.be/dQw4w9WgXcQ?si=B_RxG4f5nJ3kLmNo",
	"Watch https://youtu.be/dQw4w9WgXcQ?si=Zk3pXq7LwT9mRbV2",
	"Listen https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=PLAbCdEfGhIjKlMnOpQrStUvWxYz012345",
	"Song https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT?si=1a2b3c4d5e6f7a8b",
	"Design https://www.figma.com/design/AbCdEfGhIjKl/App?node-id=12-345&t=Qx7LmN2pR8sT4vW9-0",
	"Post https://www.instagram.com/p/C9xYz12AbCd/?igsh=RVhBTVBMRTAxMjM0NTY3ODk=",
	"Read https://example.com/article?fbclid=IwAR2xYzAbCdEfGh1234567890IjKlMnOp",
	"Ticket https://acme.atlassian.net/browse/PROJ-123?atlOrigin=eyJpIjoiMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYiLCJwIjoiaiJ9",
	"Place https://www.google.com/maps/place/Cafe/@55.75,37.61,17z?entry=ttu&g_ep=EgoyMDI0MDkxMC4wIKXMDSoASAFQAw%3D%3D",
	"Buy https://www.amazon.com/dp/B08N5WRWNW?pd_rd_r=1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d&th=1",
	"File https://drive.google.com/open?id=1AbCdEfGhIjKlMnOpQrStUvWxYz0123456",
	"Doc https://docs.google.com/document/d/1AbCdEfGhIjKlMnOpQrStUvWxYz0123456/edit?usp=sharing",
	"Track https://www.ups.com/track?tracknum=1Z999AA10123456784",
	"Track https://www.dhl.com/ru-en/home/tracking.html?tracking-id=JD000000000000000000",
	"https://example.com/?utm_source=newsletter&utm_campaign=autumn_sale_2026_week3",
	"Tweet https://x.com/user/status/1834567890123456789?s=46&t=AbCdEfGhIjKlMnOpQrStUv",
	"Ozon https://www.ozon.ru/product/chaynik-123456789/?asb=AbCdEfGhIj1234567890KlMn&avtc=1",
	"Meeting 10:30 https://meet.google.com/abc-defg-hij",
	"Tasks: buy milk",
	"Note: call mom",
	"Ключ: забрать у консьержа",
	"Ключи: отдать соседу",
	"Код от домофона: спросить у соседей",
	"Door code: ask the host",
	"Access code: pending, call support",
	"SMS code: не приходит, написать в поддержку",
	"PIN for the new card: set it up in the app",
	"Token for API: renew next week",
	"Пин-код: забыла, сходить в банк",
	"Pass CompTIA Security+ exam",
	"Enable OTP before 2027",
	"Backup code rotation 2026",
	"Pick up conference pass A3F9",
	"Boarding pass: seat 12B",
	"Ski pass: top up online",
	"Season pass: renew before May",
	"Please reset the password for user123",
	"Reset password for user123",
	"Сбросить пароль для user123",
	"Get boarding pass for flight SU1234",
	"Move passwords from Chrome to 1Password",
	"Pin issue #4821 to the board",
	"Return Amazon order 114-0000000-0000000",
	"Вернуть заказ Ozon 12345678-0001",
	"Код заказа 123456 забрать в пятницу",
	"Номер заказа 482913",
	"Трек-номер RB123456789CN",
	"Позвонить +7 900 000-00-00",
	"Позвонить 8 900 000 00 00",
	"Позвонить +0000000000000",
	"Оплатить счёт 40817810000000000000",
	"Купить молоко за 1 299 руб",
	"Встреча 15.10 в 14:30 кв. 45 подъезд 2",
	"Secret Santa budget 5000",
	"Секретный Санта бюджет 100000",
	"Ключ от ячейки A12B забрать",
	"ISBN 978-3-16-148410-0 заказать",
	"Промокод SUMMER2026 до 31.10",
	"Сменить пароль до 15 октября",
	"Buy tokens for metro 2 pcs",
	"Пароль: забыла, сходить в банк",
	"Password: ask the host",
	"API key: pending",
	"Токен: обновить в пятницу",
	"Reddit https://www.reddit.com/r/golang/comments/1abcdef/token_bucket/?share_id=Xk2pL9qRtV7mZ3nB8wYc4&utm_medium=ios_app",
	"X https://x.com/user/status/1834567890123456789?s=46&t=Xk2pL9qRtV7mZ3nB8wYc4A",
	"LinkedIn https://www.linkedin.com/posts/example_ai-activity-7241234567890123456-AbCd?utm_source=share&rcm=ACoAAAbCdEfGhIjKlMnOpQrStUvWxYz0123456",
	"AliExpress https://aliexpress.ru/item/100500.html?spm=a2g2w.productlist.search_results.0",
	"Order #112-3456789-1234562 arriving Tuesday",
	"AliExpress https://aliexpress.ru/item/1005006141234567.html",
	"Secret: ask Anna",
	"Пароль: сменить до пятницы",
	"Password: reset tomorrow",
	"Pwd: see 1Password",
	"PIN: забыла",
	"AliExpress sku https://aliexpress.ru/item/x.html?sku_id=12000036001234567",
	"Order #112-3456789-1234566 arriving Tuesday",
	"Order 112-3456789-1234566",
	"Вернуть заказ Amazon 112-3456789-1234562",
	"Заказ 4276123456789012",
	"Счет INV4111111111111111",
}

// aiSecretCorpusLimits are the known limitations, each asserting what the
// check says today and why: fixing one, or making another, shows up here.
var aiSecretCorpusLimits = []struct{ text, kind, why string }{
	// Secrets the check misses, though it should not.
	{"Pass Qwerty123!", "", "a title that opens with \"pass\" reads as the verb unless a word such as \"wifi\" or \"от\", or a colon, follows"},
	{"-----BEGIN PGP PRIVATE " + "KEY BLOCK-----", "", "the header alone; the key body under it is caught as a long random-looking token"},
	{"network security key: Kv45dacha!", "", "\"security\" does not make \"key\" the name of a credential"},

	// Secrets missed by design: shapes too close to ordinary titles to call.
	{"seed phrase abandon ability able about above absent absorb abstract absurd abuse access accident", "", "no word list for seed phrases"},
	{"домофон 45К1234", "", "\"домофон\" alone names no credential"},
	{"СНИЛС 000-000-000 00, паспорт 0000 000000", "", "identity document numbers are not credentials the check knows"},
	{"SMS code 2019", "", "a year after the name of a code sent by SMS reads as a year"},
	{"СМС-код 2019", "", "a year after the name of a code sent by SMS reads as a year"},
	{"verification code 1987", "", "a year after the name of a verification code reads as a year"},
	{"2FA-код 482913", "", "a code named in one hyphenated word is read only for a PIN or an SMS code"},
	{"Ввод СМС-кода 482913", "", "a code sent by SMS named in one hyphenated word is read only as code, codes or код"},
	{"Pool pass 4821", "", "a pool pass is a pass unless a colon or \"is\" says what it holds"},
	{"Event pass Kv45dacha!", "", "an event pass is a pass unless a colon or \"is\" says what it holds"},
	{"Пароль от wifi: ночь", "", "after a colon, a word that reads as an infinitive is taken for an instruction"},
	{"Пароль: сети", "", "after a colon, a word that reads as an infinitive is taken for an instruction"},
	{"Reset password for a b c d e f g h i Qwerty123!", "", "the account a password is reset for is skipped for a few words at most"},
	{"wifi password is sunshine", "", "a value of letters alone needs a colon to count"},
	{"Логин admin пароль qwerty", "", "a value of letters alone needs a colon to count"},
	{"Сейф: 7391", "", "no word names the credential"},
	{"Wi-Fi гостевая: Guest_5G / Welcome2024!", "", "no word names the credential"},
	{"ssh admin:Qwerty123@192.168.1.1", "", "no scheme makes it a link, and no word names the credential"},
	{"Router login admin/admin", "", "a value of letters alone, and no word names the credential"},
	{"OTP 2019", "", "a year after \"OTP\" reads as a year"},

	// Ordinary titles the check flags.
	{"Reset passwords for alice01 and bob02", "a password or secret", "after the account, a second account that looks like a value reads as the new password"},
	{"API key: rotate before Friday", "a password or secret", "a word after the colon that is not a known instruction reads as the value"},
	{"Secrets: move to Vault", "a key or token", "a word after the colon that is not a known instruction reads as the value"},
	{"Password: expires in 3 days", "a password or secret", "a word after the colon that is not a known instruction reads as the value"},
	{"Wifi password: sticker on the router", "a password or secret", "a word after the colon that is not a known instruction reads as the value"},
	{"Пароль от wifi: наклейка на роутере", "a password or secret", "a word after the colon that is not a known instruction reads as the value"},
	{"Bug: token: null after refresh", "a key or token", "a word after the colon that is not a known instruction reads as the value"},
	{"Пароль: смена раз в 90 дней", "a password or secret", "a word after the colon that is not a known instruction reads as the value"},
	{"Ключ: Пете отдать", "a key or token", "a word after the colon that is not a known instruction reads as the value"},
	{"Пароль от почты: истекает 20.10", "a password or secret", "a word after the colon that is not a known instruction reads as the value"},
	{"Tokens: store in keychain", "a key or token", "a word after the colon that is not a known instruction reads as the value"},
	{"PIN: new card arrives Monday", "a PIN or code", "a word after the colon that is not a known instruction reads as the value"},
}

func TestAISecretKindCorpus(t *testing.T) {
	seen := map[string]bool{}
	once := func(text string) {
		if seen[text] {
			t.Errorf("%q is in the corpus twice", text)
		}
		seen[text] = true
	}
	for _, c := range aiSecretCorpusCaught {
		once(c.text)
		if got := AISecretKind(c.text); got != c.kind {
			t.Errorf("AISecretKind(%q) = %q, want %q", c.text, got, c.kind)
		}
	}
	for _, text := range aiSecretCorpusOrdinary {
		once(text)
		if got := AISecretKind(text); got != "" {
			t.Errorf("AISecretKind(%q) = %q, want no secret", text, got)
		}
	}
	for _, c := range aiSecretCorpusLimits {
		once(c.text)
		if got := AISecretKind(c.text); got != c.kind {
			t.Errorf("AISecretKind(%q) = %q; a known limitation (%s) said %q, so move the row if the change is meant",
				c.text, got, c.why, c.kind)
		}
	}
}
